name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CUSTOM_VARIABLE: 'your_custom_value'
      JAVA_VERSION: '17'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: Make gradlew executable
      run: |
        chmod +x gradlew
      working-directory: path/to/your/project

    - name: Build with Gradle
      run: |
        echo "Using custom variable: $CUSTOM_VARIABLE"
        ./gradlew build
      working-directory: path/to/your/project
