name: Gradle_Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '4.10.1'

    - name: Execute Gradle build
      run: ./gradlew clean build -PbuildVersion=${{ github.event.inputs.version }}
      env:
        USERNAME_GITHUB: ${{ secrets.USERNAME_GITHUB }}
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    #- name: Set up JDK 11
     # uses: actions/setup-java@v3
      #with:
       # java-version: '11'
        #distribution: 'temurin'

   # - name: Run SonarQube analysis with JDK 11
    #  run: ./gradlew sonarqube -Dorg.gradle.java.home="$JAVA_HOME"
     # env:
      #  JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
       # SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #  - name: List generated WAR files
   #   run: ls build/libs
 
    - name: Run SonarQube Scan
      run: |
          echo "SONAR URL - > " ${{ secrets.SONAR_HOST_URL }}
          ./gradlew sonarqube \
            -Dsonar.projectKey=test-gradle-project \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
    - run: ./gradlew build
